language: node_js
sudo: enabled

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

Dependencies:
npm install node-gyp -g

apt-get install python
apt-get install make
apt-get install g++